deadlines:
  '3':
    Wed:
      date: 2024/01/24 11:00am 
      content: ip1
  '4':
    Wed:
      date: 2024/01/31 11:00am 
      content: tp1
  '6':
    Wed:
      date: 2024/02/14 11:00am
      content: tp2
  '7':
    Wed:
      date: 2024/02/21 11:00am
      content: ip2
  '8':
    Wed:
      date: 2024/02/28 11:00am
      content: tp3
  '14':
    Wed:
      date: 2024/04/10 11:00am
      content: tp4
dates:
  firstMonday: 2024/01/08
  numWeeks: 15
types:
  default:
    className: lesson
  holiday:
    className: holiday